version: '3'

services:
  dev:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: style-bert-vits2:2.2
    container_name: style-bert-vits2
    working_dir: /Style-Bert-VITS2
    tty: true
    ports:
      - "7860:7860"
    entrypoint: sh -c "python app.py --server-name 0.0.0.0"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]